const portfolioData = [
{
id: 1,
type: "ADN Sonore",
title: "ADN Sonore 1",
coverImage: "/cover/cover_adn_1.PNG",
videoFile:"https://res.cloudinary.com/dynpasxkm/video/upload/v1763638756/ADN_SONORE_1_qexaen.mov",
soundFile: "/audio/ADN_sonore_1.wav",
duration: "00:59",
},
{
id: 2,
type: "ADN Sonore",
title: "ADN Sonore 2",
coverImage: "/cover/cover_adn_2.PNG",
videoFile:"https://res.cloudinary.com/dynpasxkm/video/upload/v1763638810/ADN_SONORE_2_hkwlru.mov",
soundFile: "/audio/ADN_sonore_2.wav",
duration: "00:35",
},
{
id: 3,
type: "ADN Sonore",
title: "ADN Sonore 3",
coverImage: "/cover/cover_adn_3.PNG",
videoFile:"https://res.cloudinary.com/dynpasxkm/video/upload/v1763638804/ADN_SONORE_3_ln1n2o.mov",
soundFile: "/audio/ADN_sonore_3.wav",
duration: "00:35",
},
{
id: 4,
type: "ADN Sonore",
title: "ADN Sonore Electro",
coverImage: "/cover/cover_adn_electro.PNG",
videoFile:"https://res.cloudinary.com/dynpasxkm/video/upload/v1763638831/ADN_SONORE_%C3%89L%C3%89TRO_rll3n2.mov",
soundFile: "/audio/ADN_sonore_electro.wav",
duration: "00:35",
},
{
id: 5,
type: "ADN Sonore",
title: "ADN Sonore Funk",
coverImage: "/cover/cover_adn_funk.PNG",
videoFile:"https://res.cloudinary.com/dynpasxkm/video/upload/v1763638829/Exemple_ADN_Sonore_FUNK_b8vt9u.mov",
soundFile: "/audio/ADN_sonore_funk.wav",
duration: "00:35",
},
{
id: 6,
type: "Jingle",
title: "Jingle",
coverImage: "/cover/cover_jingle_1.PNG",
videoFile: "https://res.cloudinary.com/dynpasxkm/video/upload/v1763638825/Exemple_Jingle_dmljza.mov",
soundFile: "/audio/jingle.wav",
duration: "00:35",
},
{
id: 7,
type: "musique événementielle",
title: "Musique pour Défilé",
coverImage: "/cover/cover_defile_brutaliste.PNG",
videoFile:"https://res.cloudinary.com/dynpasxkm/video/upload/v1763730469/Exemple_d%C3%A9fil%C3%A9_Brutaliste_i6utjd.mov",
soundFile: "/audio/musique_pour_defile.wav",
duration: "00:35",
},
{
id: 8,
type: "musique événementielle",
title: "Musique boucle Planante",
coverImage: "/cover/cover_boucle_planant.PNG",
videoFile:"https://res.cloudinary.com/dynpasxkm/video/upload/v1763730485/Exemple_boucle_Planant_ddnbj9.mov",
soundFile: "/audio/boucle_planant.wav",
duration: "00:35",
},
];

export default portfolioData;
